Feature Styling
taldr27/BookStore pull request #5
Opened 2022-11-17 18:45 UTC by taldr27

### BookStore: Added some styles corrections.
In this milestone of the BookStore project I:
- Added styles following the [Zeplin design](https://app.zeplin.io/project/5b35a9e13227086040f8eb75/screen/5b695e29bb8c844f118f9378).
- Added styles corrections to the navBar.
- Added inline styles to some of the progression chapters.

2022-11-17 19:10 UTC, danmainah requested changes
Hi @taldr27 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-11-17 19:10 UTC, danmainah commented on src/components/Book.js
> +                    <button style={{ marginTop: '1em', width: '70%' }} type="button">Update progress</button>
- [x] @taldr27 great work in your styling however it's bad practice to use inline styling in your components, instead, I would recommend you create a variable for your style and then pass it to react style eg
```
const myComponentStyle = {
  color: 'blue',
  lineHeight: 10,
  padding: '1.5em',
}

function MyComponent(){

    return <div style={myComponentStyle}> Inline Styled Component</div>

}

```

2022-11-17 19:10 UTC, danmainah commented on src/pages/Categories.js
> +//     .then((json) => console.log(json));
- [x] Kindly remove the commented code, its bad practise to have commented code in your codebase.

2022-11-17 19:10 UTC, danmainah commented on src/components/Book.js
> +                    <button style={{ marginTop: '1em', width: '70%' }} type="button">Update progress</button>
- [ ] @taldr27 great work in your styling however this section color doesn't match the zeplin one given, check the comparison below:


Zeplin Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/61408860/202536578-032659cf-b552-41a1-a599-169f66a41a92.png) |  ![image](https://user-images.githubusercontent.com/61408860/202536701-522cf73c-b559-46d8-bd02-a68c1d45ada4.png)

2022-11-18 02:49 UTC, Reem-lab approved these changes
# Hi @taldr27, 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🚀🔥🎉🎉 
<img src="https://media2.giphy.com/media/G7lfJRrvdhtxK8OVGy/giphy.gif"/>

## Highlights
- No Linters error ✅
- Followed Git flow ✅
- Great working on the design  ✅
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-18 03:28 UTC, merged